---
server:
  port: 9090
spring:
  application:
    name: blog-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: blog-service
          uri: http://localhost:8080
          predicates:
            - Path=/auth/**,/users/**,/posts/**,/comments/**,/likes/**,/tags,/memberships/**,/dashboard/**
          filters:
            - AuthenticationFilter
        - id: payment-service
          uri: http://localhost:8081
          predicates:
            - Path=/payments/**
          filters:
            - AuthenticationFilter
        - id: notification-service
          uri: http://localhost:8082
          predicates:
            - Path=/notifications/**
          filters:
            - AuthenticationFilter

  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka/
